### ISSUE TITLE
How do I build this?

### ISSUE THREAD

**Issue by ghost** [FlafyDev/guifetch#2]
I'm not very smart so plz help

**Comment by FlafyDev** [comment]
## If you don't have the Nix package manager:
1. Install and setup Flutter to build for Linux desktop.
2. Make sure you've setup everything correctly by doing `flutter doctor` and checking that `Linux toolchain - develop for Linux desktop` is not showing any errors.
3. Clone this project and run `flutter build linux`
4. Program should now be in `./build/linux/x64/release/bundle/guifetch`

## If you have the Nix package manager:
1. Clone the project
2. Run `nix build`
